/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class Intro_Form extends javax.swing.JFrame {

    /*
    
    
    
     * Creates new form Intro_Form
     */
    
    

    

static MySQLCon con  = new MySQLCon(); 
    
    public Intro_Form() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        Btn_signin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        jUsername.setText("Username");
        getContentPane().add(jUsername);
        jUsername.setBounds(350, 290, 390, 30);

        jPassword.setText("Password");
        getContentPane().add(jPassword);
        jPassword.setBounds(350, 370, 400, 30);

        Btn_signin.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_accesar.png")); // NOI18N
        Btn_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_signinActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_signin);
        Btn_signin.setBounds(420, 440, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_salir_xs.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 480, 100, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/Pantallas_sin_botones/EntradaGob_sinB.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 580);

        jButton1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_salir_xs.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 480, 110, 70);

        setBounds(0, 0, 858, 616);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_signinActionPerformed
        // TODO add your handling code here:
        {
        String Password, User;
        MySQLCon con  = new MySQLCon(); 
        int index = 0,ID;
        
        
        Password = jPassword.getText();
        User = jUsername.getText();
            try {
                index = con.getIntroValues("Cuentas",User,Password);
            } catch (SQLException ex) {
                Logger.getLogger(Intro_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
        switch (index){
            case 1: 
                this.setVisible(false);
                new MenuAdm_Form().setVisible(true);
                
                Main.acceso = 1;
                break;
                
                
            case 2:
                this.setVisible(false);
                new Analista_Form().setVisible(true);
                Main.acceso = 2;
                break;
                
            case 3: 
                this.setVisible(false);
                new Empleado_Form().setVisible(true);
                
                Main.acceso = 3;
                break;
                
            case 4: 
                this.setVisible(false);
                new Metodo_Form().setVisible(true);
                
                Main.acceso = 4;
                break;
                
            default:
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña invalida, favor de reintentar");

                break;
        
        
        
        }
        
    
        //new Mapa_Form().setVisible(true);
    }
    }//GEN-LAST:event_Btn_signinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    con.closeConnection();
    System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_signin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}

