/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

/**
 *
 * @author daniel
 */
public class Mapa_Form extends javax.swing.JFrame {

    /**
     * Creates new form Mapa_Form
     */
    public Mapa_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnNorte = new javax.swing.JButton();
        BtnCuna = new javax.swing.JButton();
        BtnCitricola = new javax.swing.JButton();
        BtnSur = new javax.swing.JButton();
        BtnArqueologica = new javax.swing.JButton();
        BtnMetro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_regreso_xs.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 510, 110, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/Pantallas_sin_botones/Regiones.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 580);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 500, 140, 70);

        BtnNorte.setText("btnNorte");
        BtnNorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNorteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNorte);
        BtnNorte.setBounds(350, 20, 140, 160);

        BtnCuna.setText("jButton1");
        BtnCuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCunaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCuna);
        BtnCuna.setBounds(450, 200, 150, 60);

        BtnCitricola.setText("jButton1");
        BtnCitricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitricolaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCitricola);
        BtnCitricola.setBounds(410, 280, 210, 100);

        BtnSur.setText("jButton1");
        BtnSur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSurActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSur);
        BtnSur.setBounds(330, 330, 120, 230);

        BtnArqueologica.setText("jButton1");
        BtnArqueologica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnArqueologicaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnArqueologica);
        BtnArqueologica.setBounds(280, 170, 150, 80);

        BtnMetro.setText("jButton1");
        BtnMetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMetroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMetro);
        BtnMetro.setBounds(350, 243, 90, 50);

        setBounds(0, 0, 871, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNorteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RNorte_Form().setVisible(true);
    }//GEN-LAST:event_BtnNorteActionPerformed

    private void BtnCunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCunaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RCuna_Form().setVisible(true);
    }//GEN-LAST:event_BtnCunaActionPerformed

    private void BtnCitricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitricolaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RCitricola_Form().setVisible(true);
    }//GEN-LAST:event_BtnCitricolaActionPerformed

    private void BtnSurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSurActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RSur_Form().setVisible(true);
    }//GEN-LAST:event_BtnSurActionPerformed

    private void BtnArqueologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnArqueologicaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RArqueologica_Form().setVisible(true);
    }//GEN-LAST:event_BtnArqueologicaActionPerformed

    private void BtnMetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMetroActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RMetro_Form().setVisible(true);
    }//GEN-LAST:event_BtnMetroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Empleado_Form().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnArqueologica;
    private javax.swing.JButton BtnCitricola;
    private javax.swing.JButton BtnCuna;
    private javax.swing.JButton BtnMetro;
    private javax.swing.JButton BtnNorte;
    private javax.swing.JButton BtnSur;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
