/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author robertotrevino
 */
public class NuevoDesglose extends javax.swing.JFrame {

    MySQLCon con = new MySQLCon();
    /**
     * Creates new form NuevoDesglose
     */
    public NuevoDesglose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        Direccion = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        CreateBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Nombre.setText("Nombre");
        getContentPane().add(Nombre);
        Nombre.setBounds(280, 370, 250, 28);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hotel", "Atraccion", "Restaurante"}));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 290, 240, 27);

        Direccion.setText("Dirección");
        getContentPane().add(Direccion);
        Direccion.setBounds(290, 440, 240, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monterrey", "Abasolo", "Agualeguas", "Los Aldamos","Allende","Anáhuac","Apodaca", "Aramberri", "Bustamante", "Cadereyta Jiménez","Carmen", "Cerralvo", "Ciénega de Flores", "Doctor Arroyo", "Doctor Cross", "Doctor González", "Galeana", "García", "San Pedro Garza García", "General Bravo","General Escobedo", "General Terán", "General Treviño", "General Zaragosa","China", "General Zuazua", "Guadalupe","Los Herreras", "Higueras", "Hualahuises", "Iturbide", "Juárez", "Lampazos de Naranjo", "Linares","Marín", "Melchor Ocampo", "Mier y Noriega", "Mina", "Montemorelos", "Parás", "Pesquería", "Los Ramones", "Rayones", "Ciudad Sabinas Hidalgo", "Salinas Victoria", "San Nicolás de los Garza","Hidalgo", "Santa Cataina", "Santiago","Vallecillo", "Vllaldama"}));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(300, 220, 230, 27);

        CreateBut.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_crear.png")); // NOI18N
        CreateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButActionPerformed(evt);
            }
        });
        getContentPane().add(CreateBut);
        CreateBut.setBounds(580, 450, 220, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_regreso_xs.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 110, 110, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/P_AgregarDato.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 540);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 110, 120, 80);

        setBounds(0, 0, 835, 562);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButActionPerformed
     String d, e, Nom, Dir;
        d = (String)jComboBox1.getSelectedItem();
        e = (String)jComboBox2.getSelectedItem();
        
        Nom = Nombre.getText();
        Dir = Direccion.getText();
        
        try {
            con.enterNewDesglosadas(con.getIndex(e), d, Nom, Dir);
        } catch (SQLException ex) {
            Logger.getLogger(NuevoDesglose.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //JOptionPane.showMessageDialog(null, "Datos almacenados de forma exitosa");
        this.setVisible(false);
        if(Main.acceso == 1)
            new MenuAdm_Form().setVisible(true);
        else if(Main.acceso == 3)
            new Empleado_Form().setVisible(true);
        
    }//GEN-LAST:event_CreateButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        switch(Main.acceso) {
            case 1:
                new MenuAdm_Form().setVisible(true);
                
                break;
                
            case 3:
                new Empleado_Form().setVisible(true);
                break;
                
                  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoDesglose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoDesglose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoDesglose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoDesglose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoDesglose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBut;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
