/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RArqueologica_Form extends javax.swing.JFrame {

    /**
     * Creates new form RArqueologica_Form
     */
    public RArqueologica_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnMina = new javax.swing.JButton();
        BtnHidalgo = new javax.swing.JButton();
        BtnAbasolo = new javax.swing.JButton();
        BtnSalinas = new javax.swing.JButton();
        BtnHigueras = new javax.swing.JButton();
        BtnZuazua = new javax.swing.JButton();
        BtnCienega = new javax.swing.JButton();
        BtnCarmen = new javax.swing.JButton();
        BtnGarcia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R_Arquelogica.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 540);

        BtnMina.setText("jButton1");
        BtnMina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMina);
        BtnMina.setBounds(210, 260, 80, 30);

        BtnHidalgo.setText("jButton1");
        BtnHidalgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHidalgoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHidalgo);
        BtnHidalgo.setBounds(350, 190, 120, 30);

        BtnAbasolo.setText("jButton1");
        BtnAbasolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbasoloActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAbasolo);
        BtnAbasolo.setBounds(500, 210, 120, 20);

        BtnSalinas.setText("jButton1");
        BtnSalinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalinasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalinas);
        BtnSalinas.setBounds(390, 300, 120, 40);

        BtnHigueras.setText("jButton1");
        BtnHigueras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHiguerasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHigueras);
        BtnHigueras.setBounds(520, 360, 130, 30);

        BtnZuazua.setText("jButton1");
        BtnZuazua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZuazuaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnZuazua);
        BtnZuazua.setBounds(540, 450, 180, 29);

        BtnCienega.setText("jButton1");
        BtnCienega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCienegaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCienega);
        BtnCienega.setBounds(510, 480, 100, 50);

        BtnCarmen.setText("jButton1");
        BtnCarmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCarmenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCarmen);
        BtnCarmen.setBounds(360, 490, 140, 29);

        BtnGarcia.setText("jButton1");
        BtnGarcia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGarciaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGarcia);
        BtnGarcia.setBounds(250, 450, 100, 29);

        setBounds(0, 0, 848, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 38;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMinaActionPerformed

    private void BtnHidalgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHidalgoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 44;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnHidalgoActionPerformed

    private void BtnAbasoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbasoloActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 2;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAbasoloActionPerformed

    private void BtnSalinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalinasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 45;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSalinasActionPerformed

    private void BtnHiguerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHiguerasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 29;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnHiguerasActionPerformed

    private void BtnZuazuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZuazuaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 26;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnZuazuaActionPerformed

    private void BtnCienegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCienegaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 15;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCienegaActionPerformed

    private void BtnCarmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCarmenActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 11;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCarmenActionPerformed

    private void BtnGarciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGarciaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 18;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RArqueologica_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGarciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RArqueologica_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RArqueologica_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RArqueologica_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RArqueologica_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RArqueologica_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbasolo;
    private javax.swing.JButton BtnCarmen;
    private javax.swing.JButton BtnCienega;
    private javax.swing.JButton BtnGarcia;
    private javax.swing.JButton BtnHidalgo;
    private javax.swing.JButton BtnHigueras;
    private javax.swing.JButton BtnMina;
    private javax.swing.JButton BtnSalinas;
    private javax.swing.JButton BtnZuazua;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
