/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RCitricola_Form extends javax.swing.JFrame {

    /**
     * Creates new form RCitricola_Form
     */
    public RCitricola_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCadereyta = new javax.swing.JButton();
        BtnChina = new javax.swing.JButton();
        BtnSantiago = new javax.swing.JButton();
        BtnTeran = new javax.swing.JButton();
        BtnAllende = new javax.swing.JButton();
        BtnMontemorelos = new javax.swing.JButton();
        BtnHualahuises = new javax.swing.JButton();
        BtnLinares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R_Citricola.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 560);

        BtnCadereyta.setText("jButton1");
        BtnCadereyta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadereytaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadereyta);
        BtnCadereyta.setBounds(200, 140, 140, 40);

        BtnChina.setText("jButton1");
        BtnChina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChinaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChina);
        BtnChina.setBounds(530, 240, 80, 29);

        BtnSantiago.setText("jButton1");
        BtnSantiago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSantiagoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSantiago);
        BtnSantiago.setBounds(100, 270, 130, 29);

        BtnTeran.setText("jButton1");
        BtnTeran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTeranActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTeran);
        BtnTeran.setBounds(370, 280, 90, 40);

        BtnAllende.setText("jButton1");
        BtnAllende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllendeActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAllende);
        BtnAllende.setBounds(50, 360, 120, 30);

        BtnMontemorelos.setText("jButton1");
        BtnMontemorelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMontemorelosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMontemorelos);
        BtnMontemorelos.setBounds(190, 350, 200, 29);

        BtnHualahuises.setText("jButton1");
        BtnHualahuises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHualahuisesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHualahuises);
        BtnHualahuises.setBounds(510, 403, 170, 30);

        BtnLinares.setText("jButton1");
        BtnLinares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLinaresActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLinares);
        BtnLinares.setBounds(300, 473, 110, 30);

        setBounds(0, 0, 836, 598);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadereytaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadereytaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 10;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCadereytaActionPerformed

    private void BtnChinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChinaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 25;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnChinaActionPerformed

    private void BtnSantiagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSantiagoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 49;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSantiagoActionPerformed

    private void BtnTeranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTeranActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 22;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnTeranActionPerformed

    private void BtnAllendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllendeActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 5;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAllendeActionPerformed

    private void BtnMontemorelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMontemorelosActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 39;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMontemorelosActionPerformed

    private void BtnHualahuisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHualahuisesActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 30;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnHualahuisesActionPerformed

    private void BtnLinaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLinaresActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 34;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCitricola_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnLinaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCitricola_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCitricola_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCitricola_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCitricola_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCitricola_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAllende;
    private javax.swing.JButton BtnCadereyta;
    private javax.swing.JButton BtnChina;
    private javax.swing.JButton BtnHualahuises;
    private javax.swing.JButton BtnLinares;
    private javax.swing.JButton BtnMontemorelos;
    private javax.swing.JButton BtnSantiago;
    private javax.swing.JButton BtnTeran;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
