/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RCuna_Form extends javax.swing.JFrame {

    /**
     * Creates new form RCuna_Form
     */
    public RCuna_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnTrevino = new javax.swing.JButton();
        BtnMelchor = new javax.swing.JButton();
        BtnAldamas = new javax.swing.JButton();
        BtnCerralvo = new javax.swing.JButton();
        BtnMarin = new javax.swing.JButton();
        BtnCoss = new javax.swing.JButton();
        BtnBravo = new javax.swing.JButton();
        BtnHerreras = new javax.swing.JButton();
        BtnRamones = new javax.swing.JButton();
        BtnGonzalez = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R_Cuna_d_NL.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 830, 560);

        BtnTrevino.setText("jButton1");
        BtnTrevino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrevinoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTrevino);
        BtnTrevino.setBounds(220, 160, 190, 30);

        BtnMelchor.setText("jButton1");
        BtnMelchor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMelchorActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMelchor);
        BtnMelchor.setBounds(420, 190, 120, 40);

        BtnAldamas.setText("jButton1");
        BtnAldamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAldamasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAldamas);
        BtnAldamas.setBounds(480, 240, 170, 29);

        BtnCerralvo.setText("jButton1");
        BtnCerralvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerralvoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCerralvo);
        BtnCerralvo.setBounds(120, 280, 140, 29);

        BtnMarin.setText("jButton1");
        BtnMarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMarinActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMarin);
        BtnMarin.setBounds(20, 330, 90, 29);

        BtnCoss.setText("jButton1");
        BtnCoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCossActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCoss);
        BtnCoss.setBounds(430, 320, 110, 29);

        BtnBravo.setText("jButton1");
        BtnBravo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBravoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBravo);
        BtnBravo.setBounds(460, 400, 150, 29);

        BtnHerreras.setText("jButton1");
        BtnHerreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHerrerasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHerreras);
        BtnHerreras.setBounds(350, 460, 130, 40);

        BtnRamones.setText("jButton1");
        BtnRamones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRamonesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRamones);
        BtnRamones.setBounds(200, 420, 130, 40);

        BtnGonzalez.setText("jButton1");
        BtnGonzalez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGonzalezActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGonzalez);
        BtnGonzalez.setBounds(20, 450, 170, 29);

        setBounds(0, 0, 852, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTrevinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrevinoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 23;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnTrevinoActionPerformed

    private void BtnMelchorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMelchorActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 36;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMelchorActionPerformed

    private void BtnAldamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAldamasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 4;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAldamasActionPerformed

    private void BtnCerralvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerralvoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 12;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCerralvoActionPerformed

    private void BtnMarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMarinActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 35;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMarinActionPerformed

    private void BtnCossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCossActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 15;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCossActionPerformed

    private void BtnBravoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBravoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 20;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBravoActionPerformed

    private void BtnHerrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHerrerasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 28;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnHerrerasActionPerformed

    private void BtnRamonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRamonesActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 42;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRamonesActionPerformed

    private void BtnGonzalezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGonzalezActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 16;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RCuna_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGonzalezActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCuna_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCuna_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCuna_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCuna_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCuna_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAldamas;
    private javax.swing.JButton BtnBravo;
    private javax.swing.JButton BtnCerralvo;
    private javax.swing.JButton BtnCoss;
    private javax.swing.JButton BtnGonzalez;
    private javax.swing.JButton BtnHerreras;
    private javax.swing.JButton BtnMarin;
    private javax.swing.JButton BtnMelchor;
    private javax.swing.JButton BtnRamones;
    private javax.swing.JButton BtnTrevino;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
