/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RMetro_Form extends javax.swing.JFrame {

    /**
     * Creates new form RMetro_Form
     */
    public RMetro_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnEscobedo = new javax.swing.JButton();
        BtnSanNicolas = new javax.swing.JButton();
        BtnSanPedro = new javax.swing.JButton();
        BtnApodaca = new javax.swing.JButton();
        BtnPesqueria = new javax.swing.JButton();
        BtnJuarez = new javax.swing.JButton();
        BtnGuadalupe = new javax.swing.JButton();
        BtnMonterrey = new javax.swing.JButton();
        BtnSantaCatarina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R_Metropolitana.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 570);

        BtnEscobedo.setText("jButton1");
        BtnEscobedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscobedoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEscobedo);
        BtnEscobedo.setBounds(160, 120, 130, 40);

        BtnSanNicolas.setText("jButton1");
        BtnSanNicolas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSanNicolasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSanNicolas);
        BtnSanNicolas.setBounds(360, 140, 160, 30);

        BtnSanPedro.setText("jButton1");
        BtnSanPedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSanPedroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSanPedro);
        BtnSanPedro.setBounds(120, 210, 180, 40);

        BtnApodaca.setText("jButton1");
        BtnApodaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApodacaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnApodaca);
        BtnApodaca.setBounds(410, 220, 120, 30);

        BtnPesqueria.setText("jButton1");
        BtnPesqueria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqueriaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPesqueria);
        BtnPesqueria.setBounds(570, 270, 130, 29);

        BtnJuarez.setText("jButton1");
        BtnJuarez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJuarezActionPerformed(evt);
            }
        });
        getContentPane().add(BtnJuarez);
        BtnJuarez.setBounds(580, 343, 90, 30);

        BtnGuadalupe.setText("jButton1");
        BtnGuadalupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuadalupeActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuadalupe);
        BtnGuadalupe.setBounds(550, 410, 150, 29);

        BtnMonterrey.setText("jButton1");
        BtnMonterrey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMonterreyActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMonterrey);
        BtnMonterrey.setBounds(430, 480, 150, 29);

        BtnSantaCatarina.setText("jButton1");
        BtnSantaCatarina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSantaCatarinaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSantaCatarina);
        BtnSantaCatarina.setBounds(190, 360, 120, 50);

        setBounds(0, 0, 869, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEscobedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscobedoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 21;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnEscobedoActionPerformed

    private void BtnSanNicolasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSanNicolasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 46;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSanNicolasActionPerformed

    private void BtnSanPedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSanPedroActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 19;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSanPedroActionPerformed

    private void BtnApodacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApodacaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 7;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnApodacaActionPerformed

    private void BtnPesqueriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqueriaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 41;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnPesqueriaActionPerformed

    private void BtnJuarezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJuarezActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 32;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnJuarezActionPerformed

    private void BtnGuadalupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuadalupeActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 27;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGuadalupeActionPerformed

    private void BtnMonterreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMonterreyActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 1;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMonterreyActionPerformed

    private void BtnSantaCatarinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSantaCatarinaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 48;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RMetro_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSantaCatarinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMetro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMetro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMetro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMetro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RMetro_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnApodaca;
    private javax.swing.JButton BtnEscobedo;
    private javax.swing.JButton BtnGuadalupe;
    private javax.swing.JButton BtnJuarez;
    private javax.swing.JButton BtnMonterrey;
    private javax.swing.JButton BtnPesqueria;
    private javax.swing.JButton BtnSanNicolas;
    private javax.swing.JButton BtnSanPedro;
    private javax.swing.JButton BtnSantaCatarina;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
