/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RNorte_Form extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form RNorte_Form
     */
    public RNorte_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnAnahuac = new javax.swing.JButton();
        BtnVallecillo = new javax.swing.JButton();
        BtnLampazos = new javax.swing.JButton();
        BtnSabinas = new javax.swing.JButton();
        BtnBustamante = new javax.swing.JButton();
        BtnParas = new javax.swing.JButton();
        BtnAgualeguas = new javax.swing.JButton();
        BtnVillaldama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R_Norte.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 570);

        BtnAnahuac.setContentAreaFilled(false);
        BtnAnahuac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnahuacActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAnahuac);
        BtnAnahuac.setBounds(380, 210, 130, 20);

        BtnVallecillo.setText("jButton1");
        BtnVallecillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVallecilloActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVallecillo);
        BtnVallecillo.setBounds(520, 323, 150, 30);

        BtnLampazos.setText("jButton1");
        BtnLampazos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLampazosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLampazos);
        BtnLampazos.setBounds(240, 280, 160, 40);

        BtnSabinas.setText("jButton1");
        BtnSabinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSabinasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSabinas);
        BtnSabinas.setBounds(340, 390, 120, 40);

        BtnBustamante.setText("jButton1");
        BtnBustamante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBustamanteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBustamante);
        BtnBustamante.setBounds(140, 413, 170, 30);

        BtnParas.setText("jButton1");
        BtnParas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnParasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnParas);
        BtnParas.setBounds(540, 433, 90, 30);

        BtnAgualeguas.setText("jButton1");
        BtnAgualeguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgualeguasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAgualeguas);
        BtnAgualeguas.setBounds(480, 503, 160, 30);

        BtnVillaldama.setText("jButton1");
        BtnVillaldama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVillaldamaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVillaldama);
        BtnVillaldama.setBounds(250, 510, 150, 30);

        setBounds(0, 0, 837, 613);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVallecilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVallecilloActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 50;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnVallecilloActionPerformed

    private void BtnAnahuacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnahuacActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 6;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAnahuacActionPerformed

    private void BtnLampazosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLampazosActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 33;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnLampazosActionPerformed

    private void BtnSabinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSabinasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 45;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSabinasActionPerformed

    private void BtnBustamanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBustamanteActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 9;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnBustamanteActionPerformed

    private void BtnParasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnParasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 40;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnParasActionPerformed

    private void BtnAgualeguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgualeguasActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 3;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAgualeguasActionPerformed

    private void BtnVillaldamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVillaldamaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 51;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RNorte_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnVillaldamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RNorte_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RNorte_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RNorte_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RNorte_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RNorte_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgualeguas;
    private javax.swing.JButton BtnAnahuac;
    private javax.swing.JButton BtnBustamante;
    private javax.swing.JButton BtnLampazos;
    private javax.swing.JButton BtnParas;
    private javax.swing.JButton BtnSabinas;
    private javax.swing.JButton BtnVallecillo;
    private javax.swing.JButton BtnVillaldama;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
