/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author daniel
 */
public class RSur_Form extends javax.swing.JFrame {

    /**
     * Creates new form RSur_Form
     */
    public RSur_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnRayones = new javax.swing.JButton();
        BtnIturbide = new javax.swing.JButton();
        BtnGaleana = new javax.swing.JButton();
        BtnAramberri = new javax.swing.JButton();
        BtnZaragoza = new javax.swing.JButton();
        BtnArroyo = new javax.swing.JButton();
        BtnMier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/nuevas/R.Sur.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 570);

        BtnRayones.setText("jButton1");
        BtnRayones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRayonesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRayones);
        BtnRayones.setBounds(440, 120, 120, 29);

        BtnIturbide.setText("jButton1");
        BtnIturbide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIturbideActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIturbide);
        BtnIturbide.setBounds(490, 200, 110, 30);

        BtnGaleana.setText("jButton1");
        BtnGaleana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGaleanaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGaleana);
        BtnGaleana.setBounds(330, 210, 110, 29);

        BtnAramberri.setText("jButton1");
        BtnAramberri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAramberriActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAramberri);
        BtnAramberri.setBounds(420, 330, 140, 29);

        BtnZaragoza.setText("jButton1");
        BtnZaragoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZaragozaActionPerformed(evt);
            }
        });
        getContentPane().add(BtnZaragoza);
        BtnZaragoza.setBounds(460, 390, 130, 30);

        BtnArroyo.setText("jButton1");
        BtnArroyo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnArroyoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnArroyo);
        BtnArroyo.setBounds(370, 400, 90, 40);

        BtnMier.setText("jButton1");
        BtnMier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMierActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMier);
        BtnMier.setBounds(500, 500, 130, 50);

        setBounds(0, 0, 840, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRayonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRayonesActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 43;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnRayonesActionPerformed

    private void BtnIturbideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIturbideActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 31;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnIturbideActionPerformed

    private void BtnGaleanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGaleanaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 17;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnGaleanaActionPerformed

    private void BtnAramberriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAramberriActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 8;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnAramberriActionPerformed

    private void BtnZaragozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZaragozaActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 24;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnZaragozaActionPerformed

    private void BtnArroyoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnArroyoActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 14;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnArroyoActionPerformed

    private void BtnMierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMierActionPerformed
        // TODO add your handling code here:
        Main.codigo_mun = 37;
        this.setVisible(false);
        try { 
            new DetallesMunicipio_Form().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(RSur_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnMierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSur_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSur_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSur_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSur_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSur_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAramberri;
    private javax.swing.JButton BtnArroyo;
    private javax.swing.JButton BtnGaleana;
    private javax.swing.JButton BtnIturbide;
    private javax.swing.JButton BtnMier;
    private javax.swing.JButton BtnRayones;
    private javax.swing.JButton BtnZaragoza;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
