/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoleon3;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static nuevoleon3.MySQLCon.Conection;

/**
 *
 * @author robertotrevino
 */
public class TablaGeneral_Form extends javax.swing.JFrame {

DefaultTableModel modeloTabla;
MySQLCon con = new MySQLCon();
public static int TotHotel = 0,TotAtra = 0,TotResta = 0;
    
    public TablaGeneral_Form() throws SQLException {
        modeloTabla = new DefaultTableModel(null, getColumn());
                
          setFilas();
        
        initComponents();
    }
    
    public String[] getColumn() {
    
    String columna[] = new String[4];
columna[0] = "Municipio";
columna[1] = "Hoteles";
columna[2] = "Atracciones";
columna[3] = "Restaurantes";
    
    return columna;
    }
    
    public void setFilas() throws SQLException{
        for(int i=1; i < 52; i++){
        String Query = "SELECT Tipo FROM DesgloseMunicipios WHERE CodigoM = " + i;
        Statement st = Conection.createStatement();
            java.sql.ResultSet resultSet;
            resultSet = st.executeQuery(Query);
            String tipo = "";
            Object datos[] = new Object[4];
            while(resultSet.next())
            {
                tipo = resultSet.getString("Tipo");
                System.out.println(tipo);
                switch (tipo){
                
                    case "Hotel":
                    TotHotel++;    
                        break;
                    case "Atraccion":
                    TotAtra++;
                        break;
                        
                    case "Restaurante":
                    TotResta++;
                        break;
                
                    default:
                        System.out.println("Se escribió mal y no se reconoce el tipo");
                        break;
                }
            } 
            
            String Query2 = "SELECT Nombre FROM Ciudades WHERE CodigoM = " + i;
        Statement st2 = Conection.createStatement();
            java.sql.ResultSet resultSet2;
            resultSet2 = st2.executeQuery(Query2);
            
            
            while(resultSet2.next())
                datos[0] = resultSet2.getString("Nombre");
            
            datos[1] = TotHotel;
            datos[2] = TotAtra;
            datos[3] = TotResta;
            
            
            
            modeloTabla.addRow(datos);
            
            TotHotel = 0;
            TotAtra = 0;
            TotResta = 0;
            
            }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/B_regreso_xs.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 20, 110, 70);

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 130, 454, 404);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/robertotrevino/NetBeansProjects/NuevoLeon3/imagenes hack/Menu_Adm_sinB.png")); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 820, 570);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 10, 110, 90);

        setBounds(0, 0, 822, 592);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Metodo_Form().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaGeneral_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaGeneral_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaGeneral_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaGeneral_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TablaGeneral_Form().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TablaGeneral_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
